version: '3'

services:
  api:
    build: ./api
    ports:
      - 8000:80
    volumes:
     - './api/files:/app'
    entrypoint: ["nodemon", "server.js"]
  web:
    build: ./web
    ports:
      - 8080:3000
    volumes:
     - './web/files:/web'
    entrypoint: ["npm", "start"]